# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25e395cacea5e70c8cd07bc4c27387b5a8842ff27b39878562ba4ee61a8b5762b2b90b1365ba20a0c101488e8f5f12568a28572a2ecb7bc9bb61bfbf829c1237

test:
  secret_key_base: 56008af0ab02339b65a54d76fe16ef5dc79f13fe99586ea229b03173c09fab2358a7f5b571383a02d36e104e45f0fdfbbcfa16005c8baeceaa92cbfb50b650db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
